WoolDB/WoolDB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

WoolDB/backend/urls.py
from django.urls import path, reverse
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    # Yarns
    path('yarns', views.yarns, name='yarns'),

    path('yarns/<int:yarntype_id>',
         views.yarn_detail, name='yarn_detail'),

    path('yarns/<int:yarntype_id>/edit', views.edit_yarn,
         name='edit_yarn'),

    path('yarns/add', views.add_yarn, name='add_yarn'),

    path('yarns/<int:yarntype_id>/delete', views.delete_yarn,
         name='delete_yarn'),
    path('yarns/add/manufacturer', views.add_manufacturer_modal, name='add_manufacturer_modal'),
    path('yarns/add/material', views.add_material_modal, name='add_material_modal'),


    # Colors
    path('yarns/<int:yarntype_id>/colors/<int:color_id>',
         views.color_detail, name='color_detail'),
    path('yarns/<int:yarntype_id>/colors/add', views.add_color,
         name='add_color'),
    path('yarns/<int:yarntype_id>/colors/<int:color_id>/edit',
         views.edit_color, name='edit_color'),
    path('yarns/<int:yarntype_id>/colors/<int:color_id>/delete',
         views.delete_color, name='delete_color'),
    path('yarns/colors/add/yarnshop', views.add_yarnshop_modal, name='add_yarnshop_modal'),


    # Projectideas
    path('projectideas', views.projectideas, name='projectideas'),
    path('projectideas/add', views.add_projectidea,
         name='add_projectidea'),
    path('projectideas/<int:projectidea_id>',
         views.projectidea_detail,
         name='projectidea_detail'),
    path('projectideas/<int:projectidea_id>/edit',
         views.edit_projectidea,
         name='edit_projectidea'),
    path('projectideas/<int:projectidea_id>/delete',
         views.delete_projectidea, name='delete_projectidea'),
    path('ajax/load-colors/', views.load_colors, name='ajax_load_colors'),
    path('projectideas/<int:projectidea_id>/finished', views.projectidea_to_finishedobject,
         name='projectidea_to_finishedobject'),
    path('projectideas/add/yarn', views.add_yarn_modal, name='add_yarn_modal'),
    path('projectideas/add/color', views.add_color_modal, name='add_color_modal'),
    path('projectideas/add/yarnshop', views.add_yarnshop_collapse, name='add_yarnshop_collapse'),

    # finished objects
    path('finishedobjects', views.finishedobjects, name='finishedobjects'),
    path('finishedobjects/add', views.add_fo, name='add_fo'),
    path('finishedobjects/<int:finishedobject_id>',
         views.finishedobject_detail, name='finishedobject_detail'),
    path('finishedobjects/<int:finishedobject_id>/delete',
         views.delete_finishedobject, name='delete_finishedobject'),
    path('finishedobjects/<int:finishedobject_id>/edit',
         views.edit_fo, name='edit_finishedobject'),
    path('finishedobjects/add/projectidea', views.add_projectidea_modal, name='add_projectidea_modal'),


    # manufacturers
    path('manufacturers', views.manufacturers, name='manufacturers'),
    path('manufacturers/add', views.add_manufacturer, name='add_manufacturer'),
    path('manufacturers/<int:manufacturer_id>/delete', views.delete_manufacturer, name='delete_manufacturer'),



    # yarnshops
    path('yarnshops', views.yarnshops, name='yarnshops'),
    path('yarnshops/add', views.add_yarnshop, name='add_yarnshop'),
    path('yarnshops/<int:yarnshop_id>/delete', views.delete_yarnshop, name='delete_yarnshop'),


    # swatches
    path('swatches', views.swatches, name='swatches'),
    path('swatches/add', views.add_swatch, name='add_swatch'),
    path('swatches/<int:swatch_id>/delete', views.delete_swatch, name='delete_swatch'),

    # materials
    path('materials', views.materials, name='materials'),
    path('materials/add', views.add_material, name='add_material'),
    path('materials/<int:material_id>/delete', views.delete_material, name='delete_material'),


                ]

WoolDB/backend/models.py
from django.db import models

# Create your models here.


class Manufacturer(models.Model):
    """manufacturer of a yarn"""

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Wash(models.Model):
    """Washing instrucion"""

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Material(models.Model):
    """material/s that a yarn consists of"""

    name = models.CharField(max_length=50, unique=True)
    notes = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name


class Yarnshop(models.Model):
    """vendor where the yarn was bought"""

    name = models.CharField(max_length=50, unique=True)
    notes = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name

class Weight(models.Model):
    """Weightclass, name is pk"""

    name = models.CharField(max_length=50, unique=True, primary_key=True)

    def __str__(self):
        return self.name

class Needlesize(models.Model):
    """neeldesize in mm, name is pk"""

    name = models.CharField(max_length=50, unique=True, primary_key=True)

    def __str__(self):
        return self.name

class Yarn(models.Model):
    """type of yarn"""

    name = models.CharField(max_length=50, unique=True)
    superwash = models.BooleanField(default=False)
    yardage = models.IntegerField(blank=True, null=True)
    notes = models.CharField(max_length=200, blank=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    wash = models.ForeignKey(Wash, on_delete=models.CASCADE)
    weight = models.ForeignKey(Weight, on_delete=models.CASCADE)
    materials = models.ManyToManyField(Material)

    def __str__(self):
        return self.name

class Color(models.Model):
    """colorway of a yarn"""

    yarntype = models.ForeignKey(Yarn, on_delete=models.CASCADE)
    color = models.CharField(max_length=50)
    col_nr = models.IntegerField(null=True)
    own_it = models.BooleanField(default=False)
    quantity = models.IntegerField(blank=True, null=True, default=0)
    notes = models.CharField(max_length=200, blank=True)
    yarnshop = models.ForeignKey(Yarnshop, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        name = str(self.yarntype) + ' ' + str(self.color)
        return name


class Swatch(models.Model):
    """swatch made with a yarn"""
    name = models.CharField(max_length=50, unique=True)
    n_rows = models.IntegerField(blank=True, null=True)
    n_stitches = models.IntegerField(blank=True, null=True)
    n_rows_washed = models.IntegerField(blank=True, null=True)
    n_stitches_washed = models.IntegerField(blank=True, null=True)
    needlesize = models.ForeignKey(Needlesize, on_delete=models.CASCADE)
    yarn = models.ForeignKey(Yarn, null=True, on_delete=models.SET_NULL)
    notes = models.CharField(max_length=200, blank=True)


class Projectidea(models.Model):
    """idea for a project and yarn/color to use"""

    name = models.CharField(max_length=50, unique=True)
    link = models.CharField(max_length=200, blank=True)
    notes = models.CharField(max_length=200, blank=True)
    yardage_needed = models.IntegerField(blank=True, null=True)
    skeins_needed = models.IntegerField(blank=True, null=True)
    yarn = models.ForeignKey(Yarn, on_delete=models.CASCADE,  blank=True, null=True)
    color = models.ManyToManyField(Color, blank=True)
    weight = models.ForeignKey(Weight, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name


class FinishedObject(models.Model):
    """finished item"""

    name = models.CharField(max_length=50)
    projectidea = models.ForeignKey(Projectidea, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.CharField(max_length=50, blank=True)
    stichnr = models.IntegerField(blank=True, null=True)
    notes = models.CharField(max_length=200, blank=True)
    yarn = models.ForeignKey(Yarn, null=True, on_delete=models.SET_NULL)
    skeins_used = models.IntegerField(blank=True, null=True)
    color = models.ManyToManyField(Color, blank=True)
    needlesize = models.ManyToManyField(Needlesize)

    def __str__(self):
        return self.name

WoolDB/backend/templates/backend/add_manufacturer.html
{% extends 'backend/base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">

        </div>
        <div class="col-lg-4"></div>
    </div>

<div class="row">
<div class="container-fluid">

    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">

    <div id='form-errors'>{{ form.errors }}</div>
    {% crispy form %}


        </div>
        <div class="col-lg-4"></div>
    </div>
</div>
</div>
</div>



{% endblock %}

WoolDB/backend/templates/backend/add_manufacturer_modal.html
{% load crispy_forms_tags %}
{% block content %}


<form method="post" id="manufacturerform" action="{% url 'add_manufacturer_modal' %}" >
{{ form|crispy }}
    {% csrf_token %}
<input class="btn btn-primary" type="submit" value="Submit"  id="manufacturersubmit" >
</form>



{% endblock %}

<script type="text/javascript">

$(function() {
  $('#manufacturerform').submit(function(event) {
    event.preventDefault(); // Prevent the form from submitting via the browser
    var $form = $(this);
    console.log("On submit.");
    console.log('submitting add_manufacturer_modal');
    $.ajax({
      method: $form.attr('method'),
      url:  "{% url 'add_manufacturer_modal' %}",
      data: $form.serialize(),
      success: function(response) {
          console.log(response);
          var option = '<option value="' + response.id +
            '" selected="selected">' + response.name + '</option>';
          $('#id_manufacturer').append(option);
          $('#manufacturerdiv').collapse('hide');


      },
      error: function(response) {
        console.log(response);
      }
    });
  });
});

</script>

WoolDB/backend/templates/backend/add_projectidea_modal.html
{% load crispy_forms_tags %}
{% block content %}

 <div class="modal-dialog"  >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="YarnModalLabel">Add</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <div class="modal-body">
            {% crispy form %}

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
        </div>
        </div>
    </div>
 </div>
 </div>




<script type="text/javascript">



$(function() {



 // save the new projectidea
  $('#projectideaform').submit(function(event) {
    event.preventDefault(); // Prevent the form from submitting via the browser
    var $form = $(this);
    console.log("On submit.");
    alert('submitting add_projectidea_modal');
    $.ajax({
      method: $form.attr('method'),
      url: "{% url 'add_projectidea_modal' %}",
      data: $form.serialize(),
      success: function(response) {
          console.log(response);
          var option = '<option value="' + response.id +
            '" selected="selected">' + response.name + '</option>';
          $('#id_projectidea').append(option);
          $('#FinishedobjectModal').modal('hide');
      },
      error: function(response) {
        console.log(response);
      }
    });
  });
});





</script>
{% endblock %}

WoolDB/backend/templates/backend/add_swatch.html
{% extends 'backend/base.html' %}
 {% load crispy_forms_tags %}
{% block content %}




<div class="container-fluid">


<div class="row">
<div class="container-fluid">

    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">

    {% crispy form %}

        </div>
        <div class="col-lg-4"></div>
    </div>
</div>
</div>
</div>


<div class="modal" id="SwatchModal" tabindex="-1" role="dialog"
                                    aria-labelledby="YarnModalLabel" >
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title" id="YarnModalLabel">Add</h4>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                            <div class="modal-body">


                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="button"  class="btn btn-primary">Save changes</button>
                                            </div>
                                            </div>
                                        </div>
 </div>




<script >
// load materialform into collapsible to be shown when button is clicked
function load_materialform(){
    console.log('load_materialform');
    $('#materialsdiv').load("{% url 'add_material_modal' %}");

};

// load manufacturerform into collapsible to be shown when button is clicked
function load_manufacturerform(){
    console.log('load_manufacturerform');
    $('#manufacturerdiv').load("{% url 'add_manufacturer_modal' %}");

};



$(function() {
    // open colorform/yarnform and load form from template
    $('#swatchYarnModalButton').click(function(){
        console.log('from add_yarn_modal');
        $('#SwatchModal .modal-dialog').load("{% url 'add_yarn_modal' %}", function(){
            $('#SwatchModal').modal({show:true});
        });
    });


});

</script>



{% endblock %}

WoolDB/backend/templates/backend/add_yarn_modal.html
{% load crispy_forms_tags %}
{% block content %}

 <div class="modal-dialog"  >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="YarnModalLabel"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <div class="modal-body">
            {% crispy form %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
        </div>
        </div>
    </div>
 </div>



{% endblock %}

<script type="text/javascript">

$(function() {
    // open manufacturerform and load form from template
    $('#manufacturerModalButton').click(function(){
        console.log('from add_yarn_modal');
        $('#ProjectideaModal2 .modal-body').load("{% url "add_manufacturer_modal" %}", function(){
            $('#ProjectideaModal2').modal({show:true});
        });
    });
    $('#materialModalButton').click(function(){
        $('#ProjectideaModal2 .modal-body').load("{% url "add_material_modal" %}", function(){
            $('#ProjectideaModal2').modal({show:true});
        });
    });



  // save the new yarn
  $('#yarnform').submit(function(event) {
    event.preventDefault(); // Prevent the form from submitting via the browser
    var $form = $(this);
    console.log("On submit.");
    alert('submitting add_yarn_modal');
    $.ajax({
      method: $form.attr('method'),
      url:  "{% url 'add_yarn_modal' %}",
      data: $form.serialize(),
      success: function(response) {
          console.log(response);
          var option = '<option value="' + response.id +
            '" selected="selected">' + response.name + '</option>';
          $('#id_yarn').append(option);
          $('#ProjectideaModal').modal('hide');


      },
      error: function(response) {
        console.log(response);
      }
    });
  });
});

</script>

WoolDB/backend/templates/backend/add_yarnshop_modal.html
{% load crispy_forms_tags %}
{% block content %}

 <div class="modal-dialog"  >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="YarnModalLabel"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <div class="modal-body">
            {% crispy form %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
        </div>
        </div>
    </div>
 </div>



{% endblock %}

<script type="text/javascript">

$(function() {
  $('#yarnshopform').submit(function(event) {
    event.preventDefault(); // Prevent the form from submitting via the browser
    var $form = $(this);
    console.log("On submit.");
    $.ajax({
      method: $form.attr('method'),
      url:  "{% url 'add_yarnshop_modal' %}",
      data: $form.serialize(),
      success: function(response) {
          console.log(response);
          var option = '<option value="' + response.id +
            '" selected="selected">' + response.name + '</option>';
          $('#id_yarnshop').append(option);
          $('#ColorModal').modal('hide');


      },
      error: function(response) {
        console.log(response);
      }
    });
  });
});

</script>

WoolDB/backend/templates/backend/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WoolDB</title>
    {% load static %}
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'Backend/style.css' %}">

      <script src="{% static 'misc/html5shiv.js' %}"></script>
      <script src="{% static 'misc/respond.min.js' %}"></script>


</head>
<body>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'misc/jquery.js' %}"></script>
    <script src="{% static 'misc/jquery-3.3.1.min.js'%}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>


<div class="container-fluid">

    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-11">

<div class="page-header">
    <h1>The Wooly Mammoth Wooldatabase </h1>
    <h2>Yarns in stash, ideas for projects and finished Objects!</h2>
</div>

<nav class="navbar  navbar-light bg-light"  id="sidebar">


    <div class="collapse navbar-collapse  px-2" id="navbarSupportedContent">
        <ul class="nav nav-pills">
            <li class="nav-item active ">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a></li>
            <li class="nav-item "><a href="{% url 'yarns' %}"><strong>All yarns</strong></a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'projectideas' %}"><strong>Projectideas</strong></a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'finishedobjects' %}"><strong>Finished Objects</strong></a></li>
            <li class="nav-item"><a href="{% url 'manufacturers' %}"><strong>Manufacturers</strong></a></li>
            <li class="nav-item"><a href="{% url 'yarnshops' %}"><strong>Yarnshops</strong></a></li>
            <li class="nav-item"><a href="{% url 'swatches' %}"><strong>Swatches</strong></a></li>
            <li class="nav-item"><a href="{% url 'materials' %}"><strong>Materials</strong></a></li>
                {% if user.is_authenticated %}

                <li class="nav-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                    {% else %}
                <li class="nav-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                    {% endif %}
        </ul>
    </div>
</nav>


<div>
    {% if messages %}
    <div class="alert alert-warning alert-dismissible" role="alert">
<ul class="messages" >
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
    {{ message }}
    </li>
    {% endfor %}
</ul>
        </div>
{% endif %}
</div>

{% block content %}

{% endblock %}
            </div>

    </div>
</div>

</body>
</html>

WoolDB/backend/templates/backend/edit_color.html
{% extends 'backend/base.html' %}
{% load crispy_forms_tags %}
{% block content %}




<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <h3>Edit the color!</h3>
        </div>
        <div class="col-lg-4"></div>
    </div>

<div class="row">
<div class="container-fluid">

    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
    <form method="post" >
    {% csrf_token %}
    {{ form|crispy }}
   <button type="submit" name="Save">Save</button>
</form>
                 </div>
        <div class="col-lg-4"></div>
    </div>
</div>
</div>
</div>

{% endblock %}

WoolDB/backend/templates/backend/edit_finishedobject.html
{% extends 'backend/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <h3>Edit the Finished Object!</h3>
        </div>
        <div class="col-lg-4"></div>
    </div>

<div class="row">
<div class="container-fluid">

    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">

    <div id='form-errors'>{{ form.errors }}</div>
            <div>
                {{errors}}
            </div>
    {% crispy form %}

                             </div>
        <div class="col-lg-4"></div>
    </div>
</div>
</div>
</div>


{% endblock %}

WoolDB/backend/templates/backend/edit_manufacturer.html
{% extends 'backend/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container-fluid">


<div class="row">
<div class="container-fluid">

    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">


    {% csrf_token %}
    {% crispy form %}

                 </div>
        <div class="col-lg-4"></div>
    </div>
</div>
</div>
</div>


{% endblock %}

WoolDB/backend/templates/backend/finishedobject_detail.html
{% extends 'backend/base.html' %}
{% block content %}
<h2>{{ finishedobject }}</h2>




<div class="container-fluid">
    <div class="row align-items-center">
        <div class="col-lg-2">
            <p><a class="btn btn-primary btn-lg"
                  href="{% url 'edit_finishedobject' finishedobject.id %}"
                  role="button">Edit the finished object</a></p>
        </div>
        <div class="col-lg-2">
           <p><a class="btn btn-success btn-lg"
                  href="{% url 'add_fo' %}"
                  role="button">Add a new finished object</a></p>
        </div>
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
                 <form method="post" action="{% url 'delete_finishedobject' finishedobject.id %}">
    {% csrf_token %}
    <button class="btn btn-danger btn-lg" type="submit"  name="Delete">Delete this finished object</button>
     <input type="hidden" name="finishedobject_id" value="{{finishedobject.id}}">
</form>
        </div>
</div>
</div>


<table class="tabs">
    <tr>
        <th>name</th>
        <th>projectidea</th>
        <th>recipient</th>
        <th>stichnr</th>
        <th>notes</th>
        <th>yarn</th>
        <th>colors</th>
        <th>skeins used</th>
        <th>needlesizes</th>
    </tr>
    <tr>
        <td>{{ finishedobject.name }}</td>
        <td>{{ finishedobject.projectidea }}</td>
        <td>{{ finishedobject.recipient }}</td>
        <td>{{ finishedobject.stichnr }}</td>
        <td>{{ finishedobject.notes}}</td>
        <td>{{ finishedobject.yarn }}</td>
        <td>
            <table class="tabs">
                {% for color in finishedobject.color.all %}
                <tr>
                    <td>{{ color.color }}</td>
                </tr>
                {% endfor %}
            </table>
        </td>
        <td>{{ finishedobject.skeins_used }}</td>
        <td>
            <table class="tabs">
                {% for needle in finishedobject.needlesize.all %}
                <tr>
                    <td>{{ needle.name }}</td>
                </tr>
                {% endfor %}
            </table>
        </td>
    </tr>
</table>

{% endblock %}

WoolDB/backend/templates/backend/finishedobjects.html
{% extends 'backend/base.html' %}

{% block content %}

<h3>Finished Objects</h3>
<div class="container-fluid">
    <div class="row align-items-center">
        <div class="col-lg-1">
            <p><a class="btn btn-success btn-lg"
                  href="{% url 'add_fo' %}"
                  role="button">Add a new finished object</a></p>
        </div>
    </div>
</div>

<div class="container-fluid">
    <h3 class="mt-2">All finished objects</h3>


<table class="tabs">
    <tr>
        <th>Name</th>
        <th>Recipient</th>
        <th>Number of stitches</th>
        <th>Notes</th>
        <th>Yarn</th>
        <th>Color</th>
        <th>Number of skeins used</th>
        <th>Needlesize</th>
    </tr>
    {% for fo in finishedobjects %}
    <tr>
        <td><a href="{% url 'finishedobject_detail' fo.id %}">{{ fo.name }}</a></td>
        <td>{{ fo.recipient }}</td>
        <td>{{ fo.stichnr }}</td>
        <td>{{ fo.notes }}</td>
        <td>{{ fo.yarn }}</td>
          <td>
            <table class="tabs">
                {% for color in fo.color.all %}
                <tr>
                <td><a href="{% url 'color_detail'  fo.yarn.id color.id %}">{{ color.color }}</a></td>
                </tr>
                {% endfor %}
            </table>
        </td>

        <td>{{ fo.skeins_used }}</td>
    <td>
        <table class="tabs">
            {% for needlesize in fo.needlesize.all %}
            <tr>
                <td>{{ needlesize }}</td>
            </tr>
            {% endfor %}

        </table>
    </td>
    </tr>
    {% endfor %}
</table>




{% endblock %}

WoolDB/backend/templates/backend/index.html
{% extends 'backend/base.html' %}

{% block content %}

{% endblock %}

WoolDB/backend/templates/backend/yarnshops.html
{% extends 'backend/base.html' %}

{% block content %}

<h3>Yarnshops</h3>
<div class="container-fluid">
    <div class="row align-items-center">
        <div class="col-lg-1">
            <p><a class="btn btn-success btn-lg"
                  href="{% url 'add_yarnshop' %}"
                  role="button">Add a new yarnshop</a></p>
        </div>
    </div>
</div>

<div class="container-fluid">
    <h3 class="mt-2">All yarnshops</h3>

</div>

<table class="tabs">
    <tr>
        <th>Name</th>
        <th>Notes</th>
        <th></th>
    </tr>
    {% for yarnshop in yarnshops %}
    <tr>
        <td>{{yarnshop}}</td>
        <td>{{ yarnshop.notes }}</td>
        <td>
             <form method="post" action="{% url 'delete_yarnshop' yarnshop.id %}">
    {% csrf_token %}
    <button class="btn btn-danger btn-sm pull-right" type="submit" name="Delete">Delete this yarnshop</button>
    <input type="hidden" name="yarnshop_id" value="{{yarnshop.id}}">
</form>
        </td>
    {% endfor %}
</table>

    {% endblock %}